#!/bin/bash

IMAGE_NAME="alpine-base"

_ensure_bundle() {
  bundle config set --local path vendor/bundle
  bundle install
}

build() {
  docker build -t "${IMAGE_NAME}" .
}

_test() {
  _ensure_bundle

  bundle exec rspec
}

usage() {
  echo "Usage ${0} build | test"
}

CMD=${1:-}
shift || true
case ${CMD} in
  build) build ;;
  test) _test ;;
  *) usage ;;
esac
