name: build-push
on:
  schedule:
    - cron: "33 3 * * 2"
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: e1himself/goss-installation-action@v1.2.1
        name: Install goss/dgoss
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: alpine-base
      - name: Test
        run: dgoss run -ti alpine-base
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          tags: "ghcr.io/moritzheiber/alpine:latest"
  dependabot:
    needs: [build-push]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  trigger-container-build:
    needs: [build-push]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    name: "Trigger build for dependent containers"
    strategy:
      matrix:
        repo: ["moritzheiber/caddy-docker"]
    steps:
      - name: trigger-build-downstream
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          repository: ${{ matrix.repo}}
          event-type: container_updated
