name: build-push
on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  build-test-push:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install-deps
        run: sudo apt update && sudo apt install -y ruby-bundler
      - name: build
        run: ./run build
      - name: test
        run: ./run test
      - name: push
        env:
          GHCR_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GHCR_ACCESS_TOKEN} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          ./run push
  trigger-container-build:
    runs-on: ubuntu-20.04
    name: "Trigger build for dependent containers"
    strategy:
      matrix:
        repo: ['moritzheiber/caddy-docker', 'moritzheiber/alpine-docker']
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        name: trigger-container-builds
        with:
          repository: ${{ matrix.repo }}
          event: container_updated
          github_pat: ${{ secrets.CROSS_REPO_TOKEN }}
