name: build-push
on:
  push:
    branches:
      - main
      - pull_request
    tags-ignore:
      - "*"

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action@v1
        name: Install goss/dgoss
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: alpine-base
      - name: Test
        run: dgoss run -ti alpine-base
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "moritzheiber/alpine:latest"
  trigger-container-build:
    needs: build-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: "Trigger build for dependent containers"
    strategy:
      matrix:
        repo: ["moritzheiber/caddy-docker", "moritzheiber/alpine-docker"]
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        name: trigger-container-builds
        with:
          repository: ${{ matrix.repo }}
          event: container_updated
          github_pat: ${{ secrets.CROSS_REPO_TOKEN }}
