name: build-push
on:
  schedule:
    - cron: "33 3 * * 2"
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: e1himself/goss-installation-action@v1.1.0
        name: Install goss/dgoss
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: alpine-base
      - name: Test
        run: dgoss run -ti alpine-base
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "ghcr.io/moritzheiber/alpine:latest"
  dependabot:
    needs: [build-push]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  trigger-container-build:
    needs: build-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: "Trigger build for dependent containers"
    strategy:
      matrix:
        repo: ["moritzheiber/caddy-docker", "moritzheiber/radicale-docker"]
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        name: trigger-container-builds
        with:
          repository: ${{ matrix.repo }}
          event: container_updated
          github_pat: ${{ secrets.CROSS_REPO_TOKEN }}
